# Docker Compose override for development
version: '3.8'

services:
  # Development version of the backend with hot reload
  mve-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: mve-backend-dev
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    command: npm run dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Node.js debugging port

  # Enable LocalStack for development
  localstack:
    profiles:
      - ""  # Remove profile to enable by default